<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
  </PropertyGroup>

  <ItemGroup>
    <Page Include="**\*.xaml" SubType="Designer" Generator="MSBuild:Compile" />
    <Compile Update="**\*.xaml.cs" SubType="Code" DependentUpon="%(Filename)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Imagini\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\AuthView.xaml.cs">
      <DependentUpon>AuthView.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\DishDetailsView.xaml.cs">
      <DependentUpon>DishDetailsView.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\OrderView.xaml.cs">
      <DependentUpon>OrderView.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\DishView.xaml.cs">
      <DependentUpon>DishView.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\StockView.xaml.cs">
      <DependentUpon>StockView.xaml</DependentUpon>
    </Compile>
    <Compile Update="Views\UsersView.xaml.cs">
      <DependentUpon>UsersView.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
